# refer to https://stable-baselines3.readthedocs.io/en/master/modules/sac.html
_target_: furuta.rl.algos.TQC
# _target_: stable_baselines3.SAC
policy: "MlpPolicy"
target_update_interval: 1
learning_starts: 500
use_sde: True
use_sde_at_warmup: True
sde_sample_freq: 64
train_freq: ["1", "episode"]
gradient_steps: -1
stats_window_size: 10
