program: train.py
method: grid
parameters:
  env.encoders_CPRs:
    values: [[100, 4000.0], [211.2, 8192.0], [400.0, 16000.0]]
  seed:
    values: [1, 2, 3, 4]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
  - +experiment=sim
