program: train.py
method: grid
parameters:
  env.reward:
    values: ["alpha", "exp_alpha_1", "exp_alpha_2", "exp_alpha_4"]
  seed:
    values: [1, 2, 3]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
  - +experiment=sim
