program: train.py
method: grid
parameters:
  algo.lr:
    values: [7.3e-4, 3.0e-4, 1.0e-4]
  algo.buffer_size:
    values: [1_000_000, 300_000]
  algo.gamma:
    values: [0.99, 0.98]
  algo.tau:
    values: [0.02, 0.01]
  seed:
    values: [1, 2, 3]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
  - +experiment=sim
