program: train.py
method: grid
parameters:
  env.velocity_filter:
    values: [null, 2, 3, 4, 10]
  seed:
    values: [1, 2, 3, 4]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
  - +experiment=sim
