# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pendulum_state.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pendulum_state.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14pendulum_state.proto\"S\n\rPendulumState\x12\r\n\x05theta\x18\x01 \x01(\x02\x12\r\n\x05\x61lpha\x18\x02 \x01(\x02\x12\x11\n\ttheta_dot\x18\x03 \x01(\x02\x12\x11\n\talpha_dot\x18\x04 \x01(\x02\x62\x06proto3')
)




_PENDULUMSTATE = _descriptor.Descriptor(
  name='PendulumState',
  full_name='PendulumState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='theta', full_name='PendulumState.theta', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alpha', full_name='PendulumState.alpha', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='theta_dot', full_name='PendulumState.theta_dot', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alpha_dot', full_name='PendulumState.alpha_dot', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=107,
)

DESCRIPTOR.message_types_by_name['PendulumState'] = _PENDULUMSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PendulumState = _reflection.GeneratedProtocolMessageType('PendulumState', (_message.Message,), dict(
  DESCRIPTOR = _PENDULUMSTATE,
  __module__ = 'pendulum_state_pb2'
  # @@protoc_insertion_point(class_scope:PendulumState)
  ))
_sym_db.RegisterMessage(PendulumState)


# @@protoc_insertion_point(module_scope)
