# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pendulum_state.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14pendulum_state.proto\"\xc3\x01\n\rPendulumState\x12\x13\n\x0bmotor_angle\x18\x01 \x01(\x02\x12\x16\n\x0ependulum_angle\x18\x02 \x01(\x02\x12\x1c\n\x14motor_angle_velocity\x18\x03 \x01(\x02\x12\x1f\n\x17pendulum_angle_velocity\x18\x04 \x01(\x02\x12\x0e\n\x06reward\x18\x05 \x01(\x02\x12\x0c\n\x04\x64one\x18\x06 \x01(\x08\x12\x0e\n\x06\x61\x63tion\x18\x07 \x01(\x02\x12\x18\n\x10\x63orrected_action\x18\x08 \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pendulum_state_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PENDULUMSTATE._serialized_start=25
  _PENDULUMSTATE._serialized_end=220
# @@protoc_insertion_point(module_scope)
