# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - env: ???
  - wrappers: ???
  - algo: sac.yaml

total_timesteps: 500_000
n_envs: 12

# eval & early stopping
evaluation:
  early_stopping_reward_threshold: 930 # use null for no early stopping
  deterministic: True
  n_eval_episodes: 10
  eval_freq: 5_000 # set to null to disable evaluation and early stopping

# reproducibility
seed: 1
cudnn_deterministic: True

# plumbing/misc
debug: True
capture_video: True
wandb:
  entity: null
  project: furuta2

# resume training: load replay buffer and/or model
replay_buffer_artifact: null
model_artifact: null

# logging
save_model: True
save_replay_buffer: False
