_target_: furuta.robot.QubeDynamics
# use this file to store the sim params for the tiny version of the robot
# Motor
Rm: 6.66 # reskstance (rated voltage/stall current)
V: 12.0 # nominal voltage
km: 0.063 # back-emf constant (V-s/rad) = (rated voltage / no load speed)
# Rotary Arm
Mr: 0.035 # mass (kg)
Lr: 0.114 # length (m)
Dr: 5e-6 # viscous damping (N-m-s/rad), original: 0.0015
# Pendulum Link
Mp: 0.016 # mass (kg)
Lp: 0.08 # length (m)
Dp: 1e-6 # viscous damping (N-m-s/rad), original: 0.0005
