# slightly unsure if wrappers will be applied in the order they are listed here
# looks like the order is preserved but unsure if there could be edge cases?
# the order of the wrappers is important
TimeLimit:
  module: "gymnasium.wrappers"
  max_episode_steps: 1000

HistoryWrapper:
  module: "furuta.rl.wrappers"
  steps: 2
  use_continuity_cost: True

Monitor:
  module: "stable_baselines3.common.monitor"
