- _target_: gymnasium.wrappers.TimeLimit
  max_episode_steps: 1000
- _target_: furuta.rl.wrappers.HistoryWrapper
  steps: 4
  use_continuity_cost: True
- _target_: stable_baselines3.common.monitor.Monitor
