- _target_: gymnasium.wrappers.TimeLimit
  max_episode_steps: 400
- _target_: furuta.rl.wrappers.HistoryWrapper
  steps: 2
  use_continuity_cost: True
- _target_: stable_baselines3.common.monitor.Monitor
# - _target_: furuta.rl.wrappers.MCAPLogger
#   use_sim_time: False
#   log_dir: "../data/sim_mcap_dataset/"
