- _target_: gymnasium.wrappers.TimeLimit
  max_episode_steps: 400
- _target_: sb3_contrib.common.wrappers.time_feature.TimeFeatureWrapper
  max_steps: 400
- _target_: furuta.rl.wrappers.HistoryWrapper
  steps: 2
  use_continuity_cost: True
- _target_: stable_baselines3.common.monitor.Monitor
