# import common wrappers between sim/real
defaults:
  - base_wrappers

- _target_: furuta.rl.wrappers.GentlyTerminating
- _target_: furuta.rl.wrappers.ControlFrequency
# - _target_: furuta.rl.wrappers.MCAPLogger
#   use_sim_time: False
