# import common wrappers between sim/real
defaults:
  - base_wrappers

GentlyTerminating:
  module: "furuta.rl.wrappers"

ControlFrequency:
  module: "furuta.rl.wrappers"
# TODO update mcap logger to take terminated and truncated
# MCAPLogger:
#   module: "furuta.rl.wrappers"
#   use_sim_time: False
#   log_dir: "mcap_logs/"
