# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pendulum_state.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14pendulum_state.proto"\xc9\x01\n\rPendulumState\x12\x1f\n\x0emotor_position\x18\x01 \x01(\x0b\x32\x07.Signal\x12\x1f\n\x0emotor_velocity\x18\x02 \x01(\x0b\x32\x07.Signal\x12"\n\x11pendulum_position\x18\x03 \x01(\x0b\x32\x07.Signal\x12"\n\x11pendulum_velocity\x18\x04 \x01(\x0b\x32\x07.Signal\x12\x0e\n\x06reward\x18\x05 \x01(\x02\x12\x0e\n\x06\x61\x63tion\x18\x06 \x01(\x02\x12\x0e\n\x06timing\x18\x07 \x01(\x02"P\n\x06Signal\x12\x0f\n\x07\x64\x65sired\x18\x01 \x01(\x02\x12\x10\n\x08measured\x18\x02 \x01(\x02\x12\x10\n\x08\x66iltered\x18\x03 \x01(\x02\x12\x11\n\tsimulated\x18\x04 \x01(\x02\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "pendulum_state_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_PENDULUMSTATE"]._serialized_start = 25
    _globals["_PENDULUMSTATE"]._serialized_end = 226
    _globals["_SIGNAL"]._serialized_start = 228
    _globals["_SIGNAL"]._serialized_end = 308
# @@protoc_insertion_point(module_scope)
